apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-qvznyrwo
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-qvznyrwo:c12a4431b43db7b843f437063d86f6077f751fa7@sha256:8db3334a524b9f67512738c13d6628962d89af6699b069c65b1d30c28c1279f4
          name: container-image
